#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx

- name: upgrade OS
  ansible.builtin.apt:
    upgrade: dist

- name: update OS
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: install nginx
  ansible.builtin.apt:
    name: nginx
    state: latest

- name: copypast nginx conf
  copy:
    src: web1-nginx.conf
    dest: /etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: start nginx
  ansible.builtin.service:
    name: nginx
    state: start
    enable: yes